### ISSUE TITLE
Get active submission

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/lyric#10]
## Description
REST endpoints for getting active submission.

**Comment by leoraba** [comment]
As per last discussion, there will be 3 GET endpoints not just 1
1. `GET /submission/category/{categoryId}` Returns a summary of all Active Submissions by categoryId and user
2. `GET /submission/category/{categoryId}/organization/{organization}` Returns a summary of all Active Submissions by categoryId, organization and user
3. `GET /submission/{submissionId}` Returns an Active Submission
