### ISSUE TITLE
New Endpoint - Clear Active Submission By File Name

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/lyric#37]
Need to provide the ability for data submitters to remove active submissions by file name. 
Similiar to Argo clinical API - https://clinical.argo-qa.cumulus.genomeinformatics.org/api-docs/#/Submission/delete_submission_program__programId__clinical__versionId___fileType_

**Comment by leoraba** [comment]
Remove an entity from Submission force us to re validate updated Submission.
