### ISSUE TITLE
Add Ability to Refer Records by System ID

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/lyric#44]
## Requirements
Lyric needs to generate system IDs on its own. The delete committed data endpoint depends on this. 
The IDs are generated on commit. 
Use Nano ID as ID format:  https://www.npmjs.com/package/nanoid

**Comment by leoraba** [comment]
Added new environment variables to configure systemIds: 
- ID_USELOCAL
- ID_CUSTOM_ALPHABET
- ID_CUSTOM_SIZE

Use `ID_USELOCAL=true` to let Lyric auto generate system IDs.
