### ISSUE TITLE
Set Up ID Service in Overture Sandbox DEV

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/lyric#48]
Is there a stable version?? 
1. Set Up ID Service in Overture Sandbox DEV to test connection.
2. Set up the ID service DB in Overture sandbox dev.

**Comment by Buwujiu** [comment]
Task is blocked. No ID service deployable chart, UK is off right now, need to verify with her once she's back.

**Comment by Buwujiu** [comment]
Leo is working with UK on setting up ID service, set up the service locally first to find out proper config, then deploy to Overture dev.

**Comment by Buwujiu** [comment]
Leo has ID service running locally, still tricky to configure, and ID service only supports one dictionary at a time, as it was intended for ARGO only.

**Comment by leoraba** [comment]
ID Generator deployed in Overture Sandbox using Helm chart `overture-stack/stateless-svc`
Using Shared Song postgres Service. (Separate database name)
Root endpoint: https://id-generator.overture-sandbox.cumulus.genomeinformatics.org/

**Comment by Buwujiu** [comment]
ID service is up and running in dev, closing.
