### ISSUE TITLE
BUG :bug: - Upload Submission is not updating current Submission 

### ISSUE THREAD

**Issue by leoraba** [overture-stack/lyric#59]
## Description
Issue found on `/submission/category/{categoryId}/upload` endpoint
When there's an `OPEN/VALID/INVALID` Active Submission and we upload a second file on bellow endpoint, it creates a new Active Submission and not merging current Active Submission.

## Expected Behaviour
Merge new file with the current Active Submission. Resulting in a single Active Submission per user.

## Actual Behaviour
Creates a new Active Submission. Resulting a multiple Active Submissions per user.

**Comment by Buwujiu** [comment]
Tested in Dev, working as expected!
