### ISSUE TITLE
BUG :bug: - Register Existing Dictionary on a new category doesn't return new category 

### ISSUE THREAD

**Issue by leoraba** [overture-stack/lyric#60]
## Description
Issue found on `POST /dictionary/register` endpoint.
When Registering an existing Dictionary(name & version) on a new Category it doesn't return the new category ID

## Expected Behaviour
Response should include the new CategoryID

## Actual Behaviour
Response returns old CategoryID

**Comment by Buwujiu** [comment]
Tested in Dev, working as expected!

**Comment by Buwujiu** [comment]
Tested in Dev, working as expected.
